### PR TITLE
Changes to support cross project bigquery

### PR DESCRIPTION
**Pull request by satrox28**
Fixes for the issue https://github.com/BESTSELLER/backstage-plugin-gkeusage-backend/issues/32

### CODE REVIEW

**Review by Gaardsholt — APPROVED** [review]
LGTM - what do you say @wrighbr ?

**Comment by Gaardsholt** [comment]
@wrighbr Something else, should we add a CI job to pull requests, so it can do some kind of testing before we merge it?

**Comment by satrox28** [comment]
Hi @wrighbr can it be checked and released?.

**Review by wrighbr — APPROVED** [review]
LGTM

**Pull request merged**
